### ISSUE TITLE
Broken requirements in 3.0.1 release for iron-io/iron_core: 0.*

### ISSUE THREAD

**Issue by phansys** [iron-io/iron_mq_php#46]
[iron-io/iron_mq 3.0.1](https://packagist.org/packages/iron-io/iron_mq#3.0.1) requires iron-io/iron_core 0.* (thus it's now resolved to [0.2.1](https://packagist.org/packages/iron-io/iron_core#0.2.1) version).
This constraint breaks the app: IE, ```IronMQ::updateQueue()``` tries to use an undefined class constant ```PATCH``` (which isn't available in iron_core: 0.2.1).

**Comment by thousandsofthem** [comment]
@phansys just tagged `0.2.2.`. Hope it'll solve the issue. 
Thanks for bugreport.

**Comment by phansys** [comment]
Thank you @thousandsofthem.
