### ISSUE TITLE
When using composer, dev-master points to the wrong revision

### ISSUE THREAD

**Issue by rifflock** [iron-io/iron_mq_php#47]
Hey,
Was reworking my composer.json to work with the new releases, and it looks like instead of pointing to v1.5.3, dev-master is still pointing at 1.5.2. Just wanted to bring that to your attention

  - Updating iron-io/iron_core (dev-master d5afdcc => 1.0.0)
    Checking out 650565e8ef855c53e6a9a3099fb22b76778a81a8

  - Updating iron-io/iron_mq (dev-master d9e64a6 => 1.5.2)
    Checking out d9e64a662d6ddcd4ba535c67467f0eee221804fb

Thanks

**Comment by thousandsofthem** [comment]
hey! kinda weird, because dev-master is same as 2.0.0 and not 1.5.2

**Comment by rifflock** [comment]
Yeah, I'm not sure why it was pulling 1.5.2 even after clearing out our cache and lock. We ended up hard coding it to 1.5.3 since we're not yet ready for the major version change, and that seems to have worked.

**Comment by thousandsofthem** [comment]
actually good idea to use version `1.*` , not dev-master

**Comment by rifflock** [comment]
That's the other strange thing `1.*` was also pulling `1.5.2`, so we had to use `^1.5.3`, otherwise we got the issue about `iron_core` having the wrong version
