### ISSUE TITLE
Laravel IronMQ not found.

### ISSUE THREAD

**Issue by markalanevans** [iron-io/iron_mq_php#48]
What are the dependencies we need to install? 
How?

**Comment by thousandsofthem** [comment]
https://github.com/iron-io/iron_mq_php#branches

Just lock version to `1.*`, should be enough

**Comment by melvinmt** [comment]
Thanks @thousandsofthem , saved my day

**Comment by pfeiferchristopher** [comment]
So at first I locked my version to `1.*` and then I saw that in `1.5.3` IronMQ is namespaced and the autoload is PSR-4 which Laravel doesn't support. So I went back to `1.5.2` but I'm still getting
```php
FatalErrorException in IronConnector.php line 49:
Class 'IronMQ' not found
```
And I can not figure it out.

**Comment by thousandsofthem** [comment]
1.5.3 is not namespaced, 2.0 is. the only difference between 1.5.3 and 1.5.2 is locking IronCore version to right one

**Comment by GrahamCampbell** [comment]
@thousandsofthem This is messed up because you have pushed things from v2 to the v1 branch. This needs changing. See #52.

**Comment by davzie** [comment]
Whatever is going on here is pretty messed up, just to get IronMQ working on Laravel 4.2 I've had to try around 3 - 4 different versions and still I'm presented with:

file: "/vagrant/vendor/iron-io/iron_core/IronCore.class.php"
line: 358
message: "http error: 400 | {"msg":"Version mismatch: unsupported API version '1', expected version '3', please upgrade your client. See http://docs.iron.io"}"
type: "Http_Exception"

If I ever do get this working it scares the shit out of me putting it into production.

**Comment by thousandsofthem** [comment]
@davzie library version should match MQ api host version (), https://github.com/iron-io/iron_mq_php#branches
e.g. for Laravel 4.2 and MQv3 it's `3.*`

**Comment by davzie** [comment]
Indeed. It appears that that isn't working for Laravel because Laravel 4.2 doesn't use a specific method that that API requires for deleting jobs. This changed when they updated their legacy packages to use their new API. I've since moved to SQS to solve it, perhaps I was missing something ridiculously obvious though! Thanks ;)
