### ISSUE TITLE
Branch Deletion Proposal

### ISSUE THREAD

**Issue by GrahamCampbell** [iron-io/iron_mq_php#53]
Can you just delete the v1, v2, and v3 branches? They're serving no purpose and are just breaking stuff. What's more annoying is the v1 branch doesn't even contain the v1 code.

**Comment by GrahamCampbell** [comment]
There is no point in these other branches when we have git tags.

**Comment by GrahamCampbell** [comment]
Also, laravel 5.1 will use 2.x of this library instead of 1.x btw.

**Comment by thousandsofthem** [comment]
Detailed description about these branches: https://github.com/iron-io/iron_mq_php#branches
without branches with just tags it's almost impossible to manage and update. git tags is the must still.

**Comment by GrahamCampbell** [comment]
@thousandsofthem It makes no sense to have a master branch identical to another versioned branch, infarct it's a terrible idea imo. We need either "master" OR v4, not both...

**Comment by GrahamCampbell** [comment]
Also, why on earth do you have a v3/v4. That stuff should have been a DIFFERENT package, surely? I'm struggling to understand why you are doing these things?

**Comment by GrahamCampbell** [comment]
Sorry if I sound rude, I'm just frustrated.
