### ISSUE TITLE
IronMQ (3.0.1): $default_value['host'] is not an enterprise host with v3 support 

### ISSUE THREAD

**Issue by warnerp** [iron-io/iron_mq_php#56]
Line 148, host should be:
mq-aws-us-east-1-1.iron.io

instead of:
mq-aws-us-east-1.iron.io
which results in:
Fatal error: Uncaught exception 'Http_Exception' with message 'http error: 404 | {"msg":"Not found"}' in IronCore.class.php:358

**Comment by thousandsofthem** [comment]
Done. Also, 
1) you could pass "host" manually. 
2) added PSR-4 version for MQv3, `4.0.0` branch (to avoid semver issues). Recommend switching to it. the only difference is namespaces/autoload stuff
