### ISSUE TITLE
Version mismatch: unsupported API version '1', expected version '3'

### ISSUE THREAD

**Issue by rap2hpoutre** [iron-io/iron_mq_php#70]
Reading the lumen's doc and the iron_mq_php doc, I thought I just have to use version 2.\* of iron_mq_php to make it work with lumen (laravel 5 based micro-framework). But if I try to send a message to a queue, I got this message:

```
Version mismatch: unsupported API version '1', expected version '3', 
please upgrade your client. See http://docs.iron.io
```

I don't know what I should read in http://docs.iron.io...

**Comment by thousandsofthem** [comment]
hey @rap2hpoutre 
you'll need MQv3 library version (MQv2 deprecated at this moment)
https://github.com/iron-io/iron_mq_php#branches
> unsupported API version '1', expected version '3',
means you're already querying against MQv3 host. 
Could you try library version `4.*` ?

**Comment by rap2hpoutre** [comment]
Ok thanks. But it seems laravel does not support v>2 right now, so UI have to wait or send a PR.
