### ISSUE TITLE
PHP& Upgrade - Disabling safe uploads is no longer supported

### ISSUE THREAD

**Issue by ericvanjohnson** [iron-io/iron_mq_php#73]
Started getting the following error message after upgrading to PHP7 

![Error Message](http://l.d.pr/52xW/4r0UBPta+)

`vendor/iron-io/iron_core/IronCore.class.php:257`
`curl_setopt(): Disabling safe uploads is no longer supported`

This is a Laravel 5.1 application and I installed with composer the pacakge `"iron-io/iron_mq": "~1.5"`

This Exception is being thrown when I attempt to add to the Queue. 

I Googled and found a similar issue on the [dirkgroenen/Pinterest-API-PHP Repo](https://github.com/dirkgroenen/Pinterest-API-PHP/issues/21) and his [solution](https://github.com/dirkgroenen/Pinterest-API-PHP/commit/11a2986a2d6c353ed432885511f1c848ea04d5fe)

**Comment by thousandsofthem** [comment]
Thanks! Testing the solution

**Comment by thousandsofthem** [comment]
@ericvanjohnson updated `iron_core` package, new version released.

**Comment by aik099** [comment]
Strange, but `curl_setopt` function documentation page (see http://php.net/manual/en/function.curl-setopt.php) doesn't say, that in PHP 7 you no longer can set `CURLOPT_SAFE_UPLOAD` option.

**Comment by michaelbutler** [comment]
Yes, PHP.net really needs to update their documentation.
